apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
  namespace: auth
data:
  config.yaml: |
    issuer: "https://dex.lan/dex"

    storage:
      type: "memory"

    web:
      # Dex слушает HTTP внутри, TLS делает Ingress
      http: "0.0.0.0:5556"

    # локальная БД пользователей
    enablePasswordDB: true

    # OIDC-клиент для Kubernetes Dashboard
    staticClients:
      - id: "kubernetes-dashboard"
        name: "Kubernetes Dashboard"
        secret: "dashboard-secret"
        redirectURIs:
          - "https://dashboard.lan/oauth2/callback"

    # тестовый пользователь (admin@local / admin)
    staticPasswords:
      - email: "admin@local"
        username: "admin"
        userID: "1234567890"
        # bcrypt-хэш пароля "admin"
        hash: "$2y$10$ZPj6z6C9x6OQ5YcJzS3Z2uXb9t7D5dNf1n0mZg5bF7d9k6p3QyQyS"
