apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels: {app: dex}
  template:
    metadata:
      labels: {app: dex}
    spec:
      containers:
      - name: dex
        image: ghcr.io/dexidp/dex:v2.38.0
        args: ["serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: http
          containerPort: 5556
        volumeMounts:
        - name: cfg
          mountPath: /etc/dex/cfg
      volumes:
      - name: cfg
        configMap:
          name: dex-config
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: auth
spec:
  type: ClusterIP
  selector: {app: dex}
  ports:
  - name: http
    port: 5556
    targetPort: 5556
