apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex
  namespace: auth
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: dex.lan
    http:
      paths:
      - path: /dex
        pathType: Prefix
        backend:
          service:
            name: dex
            port: { number: 5556 }
